### ISSUE TITLE
How to render the result of voxel as mesh?

### ISSUE THREAD

**Issue by duzhenjiang113** [ChrisWu1997/PQ-NET#10]
hi Rundi,
    great works!!! Could you please tell me how to render the result of voxel to mesh?
as you showed in the paper.
   best

**Comment by ChrisWu1997** [comment]
To render the mesh, we use the software KeyShot 8.0, where you can select the surface material by yourself.

**Comment by duzhenjiang113** [comment]
> To render the mesh, we use the software KeyShot 8.0, where you can select the surface material by yourself.

thanks
