### ISSUE TITLE
label of each part is inconsistent with the raw partnet

### ISSUE THREAD

**Issue by chester256** [ChrisWu1997/PQ-NET#2]
In your voxelized models, each of them has several parts represented by channels of the voxel, but I cannot figure out what the label of each channel/part is. For instance, 36354.h5 (Chair) has 9 channels/parts, but in raw partnet, model 36354 has 6 level-1 annotations, 8 level-2 annos and 12 level-3 annos, non of them is 9:
![image](https://user-images.githubusercontent.com/18751402/77908655-804b6980-72be-11ea-84a9-7ca3fb83ba2a.png)

**Comment by ChrisWu1997** [comment]
For chair category, we processed the data using level-1 annotation and further split chair legs (`chair_base` in this example) based on connectivity.

**Comment by chester256** [comment]
I see. In addition, what's the mapping between channel index and part label? For instance, voxel[0, :, :, :] corresponds to back_surface, etc

**Comment by ChrisWu1997** [comment]
The order should be consistent with the order specified in partnet annotation. But for the mapping between channel index and part label, I can't say for sure, since we give no emphasis on part semantic labels.

**Comment by chester256** [comment]
I see. Thanks a lot!
