### ISSUE TITLE
about from outside_code.libmise import MISE

### ISSUE THREAD

**Issue by duzhenjiang113** [ChrisWu1997/PQ-NET#22]
Hello, Rundi,
I would like to ask, what is the meaning of using MISE in your code. And can you briefly describe some extra information about it?
Thanks very much!!!

**Comment by ChrisWu1997** [comment]
At first I thought it could be faster (adaptive sampling) as described by the OccNet paper, so I use it. But later I found in practice it seems to still evaluate all points in the space, thus using MISE is not necessary.

**Comment by duzhenjiang113** [comment]
thanks
