### ISSUE TITLE
Voxelization code

### ISSUE THREAD

**Issue by chester256** [ChrisWu1997/PQ-NET#3]
I am trying to voxelize PartNet with more semantics. But I get some weird results.  For instance:
![image](https://user-images.githubusercontent.com/18751402/78123520-db0cce80-7440-11ea-8320-7b6648b59f0f.png)
while the voxel shown on right hand side is yours. 
My voxelization pipeline:
1, execute the command: "../binvox -d 64 -dc -aw -pb -t binvox %s " % (obj_path)
2, read the binvoxes as 3d numpy arrays, and simply combine them via np.logical_or()

It would be great if you could release your voxelization code, or tell me the method you use. Thank you very much.

**Comment by ChrisWu1997** [comment]
The voxelization code is a bit dirty and we may not be likely to release it in short time. In general, we use the lib: https://github.com/davidstutz/mesh-voxelization for voxelization. Also note that you may need to run a floodfill algorithm afterwards to make the voxelized shape solid.

**Comment by chester256** [comment]
I see. Thank you very much.

**Comment by chester256** [comment]
May I ask how do you run the floodfill algorithm? I use skimage.segmentation.flood_fill but it seems that it often fill the wrong parts. For instance I want to fill the level 1 annotation precisely but sometimes `chair_arm` will be filled by `chair_back`, etc.

**Comment by ChrisWu1997** [comment]
We use `skimage.morphology.label` to first find out the inner grids. Then for each inner grid, find its nearest boundary grid whose part label is assigned to this inner grid.

(I wanna to show you the code, but the code the on the local machine in the school, and I'm not at school due to the COVID-19...

**Comment by chester256** [comment]
Thanks for your reply. It seems that you need to iterate all inner grids, which might lead to great compuation cost. How did you implement that?

**Comment by chester256** [comment]
I have implemented it by `scipy.spatial.distance.cdist`, which is very fast. Thank you very much.

**Comment by ChrisWu1997** [comment]
Grad to hear you made it.

**Comment by ChrisWu1997** [comment]
For anyone concerned, see our voxelization code [here](https://github.com/ChrisWu1997/PQ-NET/tree/master/voxelization).
