### ISSUE TITLE
results

### ISSUE THREAD

**Issue by CRISZJ** [ChrisWu1997/PQ-NET#5]
great job ! could you please provide some generated results? thanks :-)

**Comment by ChrisWu1997** [comment]
Thanks! I just put some generated results (.obj format) [here](https://drive.google.com/drive/folders/1u2GKZ0vSUIoWkwThmkErDxkgXEap-DtB?usp=sharing). You can download our pretrained model and generate more.

**Comment by CRISZJ** [comment]
> Thanks! I just put some generated results (.obj format) [here](https://drive.google.com/drive/folders/1POevlDv4tEsKC9XDoIF62LuW2rvOfCxa?usp=sharing). You can download our pretrained model and generate more.
thanks , do you have the results that contain voxel information（.mat format） and bbox information?

**Comment by ChrisWu1997** [comment]
I'm not able to give you those direct outputs immediately. I suggest you to run our pretrained model using provided scripts and save intermediate variables ([this line](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/agent/pqnet.py#L206) for voxel and [this line](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/agent/pqnet.py#L101) for bbox).

**Comment by CRISZJ** [comment]
> I'm not able to give you those direct outputs immediately. I suggest you to run our pretrained model using provided scripts and save intermediate variables ([this line](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/agent/pqnet.py#L206) for voxel and [this line](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/agent/pqnet.py#L101) for bbox).

ok , thanks very much : -)
