### ISSUE TITLE
the result's resolution

### ISSUE THREAD

**Issue by duzhenjiang113** [ChrisWu1997/PQ-NET#6]
There are three different resolutions written in your training code, so could your network produce results with several different resolutions?
thanks

**Comment by ChrisWu1997** [comment]
Yes, our network can produce results at different resolutions (specify [this arg](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/config/config_pqnet.py#L155)). This property comes from the implicit decoder that we used, but has nothing to do with using three different resolutions in training. Multi-scale progressive training strategy is just to speed up the training and convergence (see Sec. 3.1 of [IM-NET paper](https://arxiv.org/abs/1812.02822)).

**Comment by duzhenjiang113** [comment]
thanks

**Comment by CRISZJ** [comment]
i have a question is that can we get the each part result with 32^3 resolution. thanks

**Comment by ChrisWu1997** [comment]
Yes, we can. The code does not provide a direct API for this so you need to modify the code a little bit to achieve this:

After [this for loop](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/agent/pqnet.py#L198) (before transform into global coordinates in Line 202), you will get (points, values) pairs for each part of its own local space. Then apply function [`sdf2voxel`](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/util/visualization.py#L20) to convert each part to voxel representation, and the desired resolution is passed as an argument.

**Comment by CRISZJ** [comment]
> Yes, we can. The code does not provide a direct API for this so you need to modify the code a little bit to achieve this:
> 
> After [this for loop](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/agent/pqnet.py#L198) (before transform into global coordinates in Line 202), you will get (points, values) pairs for each part of its own local space. Then apply function [`sdf2voxel`](https://github.com/ChrisWu1997/PQ-NET/blob/b09f941cc95356ebd17ae9a9f31dcb986f7cbea4/util/visualization.py#L20) to convert each part to voxel representation, and the desired resolution is passed as an argument.

ok，thank you
